# Use docker image with haskell preinstalled for running jobs
image: mfournial/waskell-env

stages: 
  - build
  - test

build:
  script:
    - stack build
  artifacts:
    paths:
      - "src-exe/compile"

test:
  only:
    - master
  script:
    - stack test --coverage
  artifacts:
    paths:
      - "/builds/waskell/compiler/.stack-work/install/**/**/**/hpc/index.html"

pages:
  stage: test
  script:
    - mv "/builds/waskell/compiler/.stack-work/install/**/**/**/hpc/index.html" public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

