# Use docker image with haskell preinstalled for running jobs
image: mfournial/waskell-env

stages: 
  - build
  - test
  - doc

build:
  script:
    - stack build
  artifacts:
    paths:
      - "src-exe/compile"

test:
  only:
    - master
  script:
    - stack test --coverage
    - mkdir WaskellTestCoverage
    - mv /builds/waskell/compiler/.stack-work/install/**/**/**/hpc/* WaskellTestCoverage/
  artifacts:
    paths:
      - "WaskellTestCoverage/"
    expire_in: 30 days

doc:
  only:
    - master
  script:
    - stack haddock
    - mkdir WaskellDocs
    - mv /builds/waskell/compiler/.stack-work/install/**/**/**/doc/* WaskellDocs
  artifacts:
    paths:
      - "WaskelDocs/"
    expire_in: 30 days
