#!/usr/bin/env bash

cp compiler.cabal compiler.cabal.RESTORE
cp stack.yaml stack.yaml.RESTORE
mv compiler.cabal compiler.cabal.local
cp compiler.cabal.gitlab compiler.cabal
mv stack.yaml stack.yaml.local
cp stack.yaml.gitlab stack.yaml
git commit compiler.cabal stack.yaml -m "Setup config files for labTS"
git push --force gitlab master
rm compiler.cabal
rm stack.yaml
mv stack.yaml.local stack.yaml
mv compiler.cabal.local compiler.cabal
rm compiler.cabal.RESTORE
rm stack.yaml.RESTORE
git commit compiler.cabal stack.yaml -m "Setup config files for origin"
