#!/usr/bin/env bash

mv compiler.cabal compiler.cabal.local
cp compiler.cabal.gitlab compiler.cabal
mv stack.yaml stack.yaml.local
cp stack.yaml.gitlab stack.yaml
git commit compiler.cabal stack.yaml -m "Setup config files for labTS"
git push --force gitlab master
git reset --hard HEAD~1
rm compiler.cabal.local
rm stack.yaml.local
rm compiler.cabal.RESTORE
rm stack.yaml.RESTORE
