#!/usr/bin/env perl

use v5.14;

use Cwd qw(cwd);
my $dir = cwd;

my @files = split("\n", `find wacc-samples/invalid/syntaxErr/**/*.wacc -type f`);

my $cnt = 0;
for my $file (@files) {
	print `../src/Bnfc/TestWacc $file`;
  $cnt++;
}
say "You have tested $cnt files";
