

module AbsWacc where

-- Haskell module generated by the BNF converter




newtype IntDigit = IntDigit ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype PlusToken = PlusToken ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype MinusToken = MinusToken ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype BoolLiteral = BoolLiteral ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype IntT = IntT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype BoolT = BoolT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype CharT = CharT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype StringT = StringT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype TimesT = TimesT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype DivideT = DivideT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype ModuloT = ModuloT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype GreaterT = GreaterT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype LessT = LessT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype GreaterEqT = GreaterEqT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype LessEqT = LessEqT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype EqT = EqT ((Int,Int),String) deriving (Eq, Ord, Show, Read)
newtype NotEqT = NotEqT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype AndT = AndT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype OrT = OrT ((Int,Int),String) deriving (Eq, Ord, Show, Read)
newtype SkipT = SkipT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype ReadT = ReadT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype PrintT = PrintT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype PrintLnT = PrintLnT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype FreeT = FreeT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype ExitT = ExitT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype LParenT = LParenT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype RParenT = RParenT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype LBracketT = LBracketT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype RBracketT = RBracketT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype IsT = IsT ((Int,Int),String) deriving (Eq, Ord, Show, Read)
newtype WhileT = WhileT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype DoT = DoT ((Int,Int),String) deriving (Eq, Ord, Show, Read)
newtype DoneT = DoneT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype IfT = IfT ((Int,Int),String) deriving (Eq, Ord, Show, Read)
newtype FiT = FiT ((Int,Int),String) deriving (Eq, Ord, Show, Read)
newtype ThenT = ThenT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype ElseT = ElseT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype EndT = EndT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype BeginT = BeginT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype PairT = PairT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype NewpairT = NewpairT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype CallT = CallT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype FstT = FstT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype SndT = SndT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype EqualT = EqualT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype LenT = LenT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype OrdT = OrdT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype ChrT = ChrT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype ReturnT = ReturnT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype NotT = NotT ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype CharLiteral = CharLiteral ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype PairLiteral = PairLiteral ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype Identifier = Identifier ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
newtype StringLiteral = StringLiteral ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
data Exp = WaccTree Program
  deriving (Eq, Ord, Show, Read)

data Program = Program BeginT [Function] [Statement] EndT
  deriving (Eq, Ord, Show, Read)

data Function
    = Function Type Identifier LParenT [Parameter] RParenT IsT [Statement] EndT
  deriving (Eq, Ord, Show, Read)

data Parameter = Param Type Identifier
  deriving (Eq, Ord, Show, Read)

data Statement
    = StatSkip SkipT
    | StatDecAss Type Identifier EqualT AssignRhs
    | StatAss AssignLhs EqualT AssignRhs
    | StatRead ReadT AssignLhs
    | StatFree FreeT Expression
    | StatReturn ReturnT Expression
    | StatExit ExitT Expression
    | StatPrint PrintT Expression
    | StatPrintLn PrintLnT Expression
    | StatIf IfT Expression ThenT [Statement] ElseT [Statement] FiT
    | StatWhile WhileT Expression DoT [Statement] DoneT
    | StatScope BeginT [Statement] EndT
  deriving (Eq, Ord, Show, Read)

data AssignLhs
    = AssignToIdent Identifier
    | AssignToArrayElem ArrayElem
    | AssignToPair PairElem
  deriving (Eq, Ord, Show, Read)

data AssignRhs
    = AssignExp Expression
    | AssignArrayLit ArrayLiteral
    | AssignPair NewpairT LParenT Expression Expression RParenT
    | AssignPairElem PairElem
    | AssignFunctionCall CallT Identifier LParenT [ArgumentList] RParenT
  deriving (Eq, Ord, Show, Read)

data ArgumentList = ArgumentList Expression
  deriving (Eq, Ord, Show, Read)

data PairElem = PairFst FstT Expression | PairSnd SndT Expression
  deriving (Eq, Ord, Show, Read)

data Type
    = BaseType BaseType
    | ArrayType ArrayDeclarationLiteral
    | PairType PairT LBracketT PairElemType PairElemType RParenT
  deriving (Eq, Ord, Show, Read)

data BaseType
    = IntType IntT
    | BoolType BoolT
    | CharType CharT
    | StringType StringT
  deriving (Eq, Ord, Show, Read)

data ArrayDeclarationLiteral
    = ArrayDeclarationLiteral Type LBracketT RBracketT
  deriving (Eq, Ord, Show, Read)

data ArrayElem = ArrayElem Identifier [ArrayAccess]
  deriving (Eq, Ord, Show, Read)

data ArrayAccess = ArrayAccess LBracketT Expression RBracketT
  deriving (Eq, Ord, Show, Read)

data ArrayLiteral
    = ArrayLiteral LBracketT [ArrayLiteralElem] RBracketT
  deriving (Eq, Ord, Show, Read)

data ArrayLiteralElem = ArrayLiteralElem Expression
  deriving (Eq, Ord, Show, Read)

data PairElemType
    = PairElemTypeBase BaseType
    | PairElemTypeArray ArrayDeclarationLiteral
    | PairElemTypePair PairT
  deriving (Eq, Ord, Show, Read)

data Expression
    = IntExp IntLiteral
    | BoolExp BoolLiteral
    | CharExpr CharLiteral
    | StringExpr StringLiteral
    | PairExpr PairLiteral
    | IdentExpr Identifier
    | ArrayExpr ArrayElem
    | UExpr UnaryOperator Expression
    | BExp Expression BinaryOperator Expression
    | BracketExp LParenT Expression RParenT
  deriving (Eq, Ord, Show, Read)

data UnaryOperator
    = UBang NotT
    | UMinus MinusToken
    | ULength LenT
    | UOrd OrdT
    | UChr ChrT
  deriving (Eq, Ord, Show, Read)

data BinaryOperator
    = BTimes TimesT
    | BDivide DivideT
    | BModulus ModuloT
    | BPlus PlusToken
    | BMinus MinusToken
    | BGreater GreaterT
    | BLess LessT
    | BGreaterEqual GreaterEqT
    | BLessEqual LessEqT
    | BEqual EqualT
    | BNotEqual NotEqT
    | BAnd AndT
    | BOr OrT
  deriving (Eq, Ord, Show, Read)

data IntLiteral
    = IntPlus PlusToken IntDigit
    | IntMinus MinusToken IntDigit
    | IntLiteral IntDigit
  deriving (Eq, Ord, Show, Read)

