#!/usr/bin/env perl

use v5.14;

use Cwd qw(cwd);
my $dir = cwd;

my @files = split("\n", `find ../../src-test/wacc-samples/valid/ -type f`);

my $cnt = 0;
for my $file (@files) {
	print `./testWacc $file`;
  $cnt++;
}
say "You have tested $cnt files";
